# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: vscode CI

on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - LICENSE

jobs:
  build:

    runs-on: ubuntu-latest # 运行该脚本的操作系统

    strategy:
      matrix:
        node-version: [12.x] # 配置所需node版本

    steps: # 自动化步骤
    - uses: actions/checkout@v2 # 拉取仓库代码到操作系统
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies  # 第二步，安装依赖
      run: npm install
    - name: Install vsce # 安装打包工具
      run: npm i -g vsce
    - name: Package # 打包
      run: vsce package -o ./vsc-gogle-translate.vsix
    - name: Create Release # 发布
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }} # 标签名
        release_name: Release ${{ github.ref }} # 发布名
        draft: false # 是否草稿
        prerelease: false # 是否预发布
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./vsc-gogle-translate.vsix
        asset_name: vsc-gogle-translate.vsix
        asset_content_type: application/zip
